#!/usr/bin/env bash

# die on all errors
set -e

# cd to script directory
cd "${0%/*}"

usage="usage: $0 <user>/<repo> <package>"

# github user and repo of plugin being installed.
user=${1%/*}
repo=${1#*/}

# name of package to install plugin into. defaults to current user.
package=${2:-$USER}

url=https://github.com/${user:?unspecified. $usage}/${repo:?unspecified. $usage}
path=vim/pack/${package:?unspecified. $usage}/start/${repo}

git submodule add "https://github.com/$user/$repo" "vim/pack/$package/start/$repo"
git commit -m "Add $repo"

