#!/usr/bin/env bash

# die on all errors
set -e

usage="usage: $0 <add|ls|rm|update> ..."
cmd=$1

if [[ -z "$cmd" ]]; then
  echo $usage
  exit
fi

shift

# cd to script directory
cd "${0%/*}"

case $cmd in
add)
  usage="usage: $0 $cmd <user>/<repo> [package]"
  
  # github user and repo of plugin being installed.
  user=${1%/*}
  repo=${1#*/}
  
  # name of package to install plugin into. defaults to current user.
  package=${2:-plugins}
  
  url=https://github.com/${user:?unspecified. $usage}/${repo:?unspecified. $usage}
  path=vim/pack/${package:?unspecified. $usage}/start/${repo}
  
  git submodule add "https://github.com/$user/$repo" "pack/$package/start/$repo"
  git commit -m "Add $repo"
  ;;
*)
  echo $usage
  ;;
esac 
