" Set <Leader> to comma
let mapleader=","

" Enable line numbers
set number

" Enable syntax highlighting
syntax on

" Use macOS clipboard
set clipboard=unnamed

" Load filetype plugin and indent
filetype plugin on
filetype indent on

"### Airline ###

" Fix not loading at startup
set laststatus=2

" Enable Powerline fonts
let g:airline_powerline_fonts = 1

"### /Airline ###
